APPLICATIONID=com.junnew
COMPILESDK=36
MINSDK=24
TARGETSDK=36
VERSIONCODE=1
VERSIONNAME=1.0.0
BASE_URL_STG=https://dev.api.example.com
BASE_URL_PROD=https://prod.api.example.com
APP_NAME=Multi Talking